name: "test-on-pr"

on:
  push:
    branches:
      - main 
  pull_request: {}

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  publish-postdata:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          
      - name: Install Tauri dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run tauri:build

       # 使用 Sigstore/Fulcio 进行代码签名
      - name: Sign Executable with Fulcio
        uses: sigstore/codesign-action@v2
        with:
          fulcio-url: https://fulcio.sigstore.dev
          files: '**/*.msi' # 替换为你需要签名的文件路径
          oidc-client-id: sigstore

      # 上传签名后的文件到 GitHub Release
      - name: Upload release assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./src-tauri/target/release/bundle/msi/tauri-test.msi
          asset_name: tauri-test_v${{ github.ref_name }}.msi
          asset_content_type: application/x-msi

