name: "test-on-pr"

on:
  push:
    branches:
      - main 
  pull_request: {}

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  publish-postdata:
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          
      - name: Install Tauri dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm tauri build

# 安装 Cosign
      - name: Install Cosign
        run: |
          curl -fsSL https://github.com/sigstore/cosign/releases/latest/download/cosign-windows-amd64.exe -o cosign.exe
          chmod +x cosign.exe

      # 使用 Fulcio 进行签名
      - name: Sign MSI using Cosign
        env:
          COSIGN_EXPERIMENTAL: "1" # 启用实验特性
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.GITHUB_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./cosign.exe version # 打印 cosign 版本信息
          ./cosign.exe sign-blob `
            --oidc-issuer=https://token.actions.githubusercontent.com `
            --fulcio-url=https://fulcio.sigstore.dev `
            --rekor-url=https://rekor.sigstore.dev `
            ./src-tauri/target/release/bundle/msi/tauri-app2_0.1.0_x64_en-US.msi
        shell: pwsh

      # 上传签名后的文件到 GitHub Release
      - name: Upload release assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./src-tauri/target/release/bundle/msi/tauri-app2_0.1.0_x64_en-US.msi
          asset_name: tauri-test_v${{ github.ref_name }}.msi
          asset_content_type: application/x-msi

